### ISSUE TITLE
skeleton does not validate, missing ul tags in nav

### ISSUE THREAD

**Issue by lkraav** [kennethreitz/wordpress-theme-skeleton#1]
offending code:
         <div id="header">
             <div id="nav">
                 <li> <a href="/">Home</a> </li>
                 <li> <a href="/gallery">Gallery</a> </li>
                 <li> <a href="/contact">Contact</a> </li>
                 <li> <a href="/etc">Etc</a> </li>
             </div>
         </div>

**Comment by kennethreitz** [comment]
Oh, thanks for finding this. I'll push an update.

**Comment by kennethreitz** [comment]
Fixed! http://github.com/kennethreitz/wordpress-theme-skeleton/commit/132d0904edd14dec54ff091f502c2dd321aa930d

Thanks again.
